<?php

$helper = $this->helper('GoMage\Navigation\Helper\Data');
$sidebarPosition = $helper->getBlockLocation($helper->getShowShopByIn());
$categoryPosition = $helper->getBlockLocation($helper->getCategoriesBlockLocation());
?>
<link rel="stylesheet" type="text/css" media="all"
      href="<?= $block->getViewFileUrl('GoMage_Navigation::css/gomage-navigation-sidebar-position-' . $sidebarPosition . '.css'); ?>">
<link rel="stylesheet" type="text/css" media="all"
      href="<?= $block->getViewFileUrl('GoMage_Navigation::css/gomage-navigation-categories-position-' . $categoryPosition . '.css'); ?>">