<?php
/**
 * @var $categoriesBlock \GoMage\Navigation\Block\Categories
 */
$helperDataCat = $this->helper('GoMage\Navigation\Helper\Data');
$categoriesHelper = $this->helper('GoMage\Navigation\Helper\CategoryData');
?>

<?php foreach ($data as $category):?>
    <?php $name = ($categoriesHelper->isShowImageName()) ? $category['name'] : ''; ?>
    <?php $image = $block->getCategoryImage($category['entity_id']); ?>
    <?php $image = $block->getImage(); ?>
    <?php $image =  $categoriesHelper->getCategoryImage($category['entity_id'])  ?>
    <ol class="gomage-tree-timage">
        <li
                data-value="<?= $helperDataCat->getValueCategory(['cat'=>strtolower($category['name'])]) ?>"
                data-categories = "1"
                data-param="cat"
                data-param-cat-parent = "<?php echo 'parent_cat_'.$category['entity_id'] ?>"
                data-cat-parent = "<?php echo $category['parent_cat'] ?>"
            <?php if ($helperDataCat->isInaCategoryRequest($category['name'], $category)) : ?>
                data-active="1"
            <?php endif; ?>
                data-ajax="<?=$categoriesBlock->escapeHtml($isAjax)?>" data-role="navigation-filter" data-type="categories-li"
                data-url="<?= $helperDataCat->getUrlCategory(['cat'=>strtolower($category['name']),'parent_cat_'.$category['entity_id']=>$category['parent_cat'] ]) ?>">
            <a href="<?=$categoriesBlock->escapeUrl($category['url'])?>"  <?php if ($helperDataCat->isInaCategoryRequest($category['name'], $category)) : ?>
                class="selected"
            <?php endif; ?>>
                <?php if($image): ?>
                    <img
                            src="<?= $categoriesHelper->resize($image) ?>"
                            width="<?=$categoriesBlock->escapeHtml($categoriesHelper->getCategoriesImageWidth())?>"
                            height="<?=$categoriesBlock->escapeHtml($categoriesHelper->getCategoriesImageHeight())?>">
                <?php endif; ?>
                <?php if($categoriesHelper->isShowImageName()): ?>
                    <span><?= $name;?></span>
                <?php endif;?>
            </a>

            <?php if (($categoriesBlock->getCategoriesDataHelper()->getShowAllSubcategories() && !empty(($category['children']))) || $helperDataCat->isInaCategoryRequest($category['name'], $category)): ?>
                <?=$categoriesBlock->getImageCategoriesList($category['children']);?>
            <?php endif;?>
        </li>
    </ol>
<?php endforeach;?>
