<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 2.0.0
 * @since     Class available since Release 2.0.0
 */

$helperDataCat = $this->helper('GoMage\Navigation\Helper\Data');
$categoriesHelper = $this->helper('GoMage\Navigation\Helper\CategoryData');
?>

<?php foreach ($data as $category) :?>
    <?php $name = ($categoriesHelper->isShowImageName()) ? $category['name'] : ''; ?>
    <?php $image = $block->getCategoryImage($category['entity_id']); ?>
    <?php $image = $block->getImage(); ?>
    <?php $image =  $categoriesHelper->getCategoryImage($category['entity_id'])  ?>
    <ol class="gomage-tree-timage">
        <li
             data-value="<?php echo  $helperDataCat
                 ->getValueCategory(['cat'=>(int)$helperDataCat->isUseFriendlyUrls()
                     ? strtolower($category['name']):$category['entity_id']]) ?>"
             data-categories = "1"
             data-param="cat"
             data-param-cat-parent = "<?php echo 'parent_cat_'.$category['entity_id'] ?>"
             data-cat-parent = "<?php echo $category['parent_cat'] ?>"
            <?php if ($helperDataCat->getValueCategory(
                [
                    'cat' => (int)$helperDataCat->isUseFriendlyUrls()
                        ? strtolower($category['name']) : $category['entity_id']
                ]
            )
            ) :
                ?>
                data-active="1"
            <?php endif; ?>
            data-ajax="<?php echo $categoriesBlock->escapeHtml($isAjax)?>"
             data-role="navigation-filter" data-type="categories-li"
            data-url="<?php echo  $helperDataCat->getUrlCategory(['cat'=>strtolower((int)$helperDataCat
                ->isUseFriendlyUrls() ?
                $category['name']: $category['entity_id']),'parent_cat_'
            .$category['entity_id']=>$category['parent_cat'] ]) ?>">
            <a href="<?php echo $categoriesBlock->escapeUrl($category['url'])?>"
                <?php if ($helperDataCat->isInaCategoryRequest((int)$helperDataCat->isUseFriendlyUrls()
                    ? $category['name']: $category['entity_id'], $category)) : ?>
                class="selected"
            <?php endif; ?>>
                <?php if ($image) : ?>
                    <img
                            src="<?php echo  $categoriesHelper->resize($image) ?>"
                            width="<?php echo $categoriesBlock
                                ->escapeHtml($categoriesHelper->getCategoriesImageWidth())?>"
                            height="<?php echo $categoriesBlock
                                ->escapeHtml($categoriesHelper->getCategoriesImageHeight())?>">
                <?php endif; ?>
                <?php if ($categoriesHelper->isShowImageName()) : ?>
                    <span><?php echo  $name;?></span>
                <?php endif;?>
            </a>

            <?php if (($categoriesBlock->getCategoriesDataHelper()->getShowAllSubcategories()
                    && !empty(($category['children']))) ||
                $helperDataCat->isInaCategoryRequest((int)$helperDataCat->isUseFriendlyUrls()
                    ? $category['name']: $category['entity_id'], $category)) : ?>
                <?php echo $categoriesBlock->getImageCategoriesList($category['children']);?>
            <?php endif;?>
        </li>
    </ol>
<?php endforeach;?>
