<?
/**
 * @var $categoriesBlock \GoMage\Navigation\Block\Categories
 */

?>

<?if(!empty($data)):?>
    <ol <?=$categoriesBlock->escapeHtmlAttr($checkboxes)?>>
        <?foreach ($data as $category):?>
            <? $active = ($currentCategoryId == $category['entity_id']) ? ' class="selected"' : '';?>
                <li
                        data-ajax="<?=$categoriesBlock->escapeHtmlAttr($isAjax)?>"
                        data-role="navigation-filter"
                        data-type="categories-li"
                        data-url="<?=$categoriesBlock->escapeUrl($category['url'])?>"
                        <? if (!empty(($category['children']))): ?> class="parent"<? endif; ?>>
                    <a href="<?=$categoriesBlock->escapeUrl($category['url'])?>"<?=$categoriesBlock->escapeHtml($active)?>><span><?=$categoriesBlock->escapeHtml($category['name'])?></span></a>
                    <? if (!empty(($category['children']))): ?>
                        <?= $categoriesBlock->getOlList($category['children']); ?>
                    <? endif; ?>
                </li>
        <?endforeach;?>
    </ol>
<?endif;?>
