<?if(!empty($data)):?>
    <ol <?=$checkboxes?>>
        <?foreach ($data as $category):?>
            <?php $active = ($currentCategoryId == $category['entity_id']) ? ' class="selected"' : '';?>
                <li
                        data-ajax="<?=$isAjax?>"
                        data-role="navigation-filter"
                        data-type="categories-li"
                        data-url="<?=$category['url']?>"
                        <? if (!empty(($category['children']))): ?> class="parent"<? endif; ?>>
                    <a href="<?=$category['url']?>"<?=$active?>><span><?=$category['name']?></span></a>
                    <? if (!empty(($category['children']))): ?>
                        <?= $categoriesBlock->getOlList($category['children']); ?>
                    <? endif; ?>
                </li>
        <?endforeach;?>
    </ol>
<?endif;?>
