<?
/**
 * @var $categoriesBlock \GoMage\Navigation\Block\Categories
 */

?>

<? foreach ($data as $category): ?>
    <? $selected = ($currentCategoryId == $category['entity_id']) ? 'selected' : ''; ?>
    <option <?= $categoriesBlock->escapeHtmlAttr($selected) ?>
            value="<?= $categoriesBlock->escapeUrl($category['url']) ?>"> <?= $categoriesBlock->escapeHtml(str_repeat('&nbsp;&nbsp;', $category['level']) . $category['name']) ?></option>
    <? if (is_array($category['children']))
        $categoriesBlock->getSelectList($category['children']);
    ?>
<? endforeach; ?>
