<ol class="items gan-filter gan-filter-categories gan-filter-default
    <?php if($block->getCategoriesDataHelper()->getCategoriesNavigationType() == \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK) echo 'gan-filter-in-block'; ?>
    <? echo ($block->getCategoriesDataHelper()->isCategoriesShowCollapsed()) ? 'filter-content-hide' : '';?>
    <?= ($block->getCategoriesDataHelper()->isShowCheckboxes()) ? 'gan-filter-checkbox' :''; ?>"
    <?php if($block->getCategoriesDataHelper()->getCategoriesNavigationType() == \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK && $block->getCategoriesDataHelper()->getMaxBlockHeightCategories()): ?> style="max-height:<?php echo $block->getCategoriesDataHelper()->getMaxBlockHeightCategories(); ?>px;"<?endif;?>>
    
    <?php
    foreach($block->getStoreCategories(true, false, true) as $category):
         if (!$category->getIsActive()) continue;?>
        <li class="item" data-ajax="<?= (int)$block->getCategoriesDataHelper()->isAjax(); ?>" data-role="navigation-filter"
            data-type="categories-li" data-url="<?= $block->getCategoryHelper()->getCategoryUrl($category) ?>">
            <a href="#"<?= ($block->getCurrentCategoryId() == $category->getId()) ? ' class="active"' : ''; ?>>
                <span class="filter-label-wrap"><?= $category->getName() ?></span>
            </a>
        </li>
    <?php endforeach; ?>
    
</ol>