<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 1.0.0
 * @since     Class available since Release 1.0.0
 */

$helperData = $this->helper('GoMage\Navigation\Helper\Data');
?>

<div class="block block-gan-categories
    <?php echo ($block->getCategoriesDataHelper()->getCategoriesNavigationType()
    == \GoMage\Navigation\Model\Config\Source\Navigation::DEFAULTS) ? 'gan-categories-default' : ''; ?>
    <?php echo ($block->getCategoriesDataHelper()->getCategoriesNavigationType() ==
    \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK) ?
    'gan-categories-default gan-categories-in-block' : ''; ?>
    "
    style="background-color: <?php echo $block
        ->escapeHtml($block->getNavigationViewHelper()->getNavigationViewBlockCategoriesBackgroundColor())?>"
>
    <div class="block-title gan-categories-title" data-role="navigation-filter" data-type="categories-content">
        <strong><?php echo __('Categories') ?></strong>
    </div>
    <div class="block-content block-content-gan-categories"<?php if ($block->getCategoriesDataHelper()
            ->getCategoriesNavigationType() ==
        \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK &&
        $block->getCategoriesDataHelper()->getMaxBlockHeightCategories()) : ?>
        style="max-height:<?php echo $block->escapeHtml($block->getCategoriesDataHelper()
            ->getMaxBlockHeightCategories()); ?>px;
            "<?php endif; ?>>
        <div class="block-content-in"<?php echo ($block->getCategoriesDataHelper()->isCategoriesShowCollapsed())
            ? ' style="display:none;"' : '';?>>
            <ul class="gan-categories-list<?php echo ($block->getCategoriesDataHelper()->isShowCheckboxes()) ?
                ' gan-categories-list-checkbox' : '' ; ?>">
                <?php
                foreach ($block->getStoreCategories() as $category) :
                    foreach ($block->getCategoriesSearch($category) as $cat) :
                        if (!$category->getIsActive() || $block->isHidecategory($cat)) {
                            continue;
                        }?>
                        <?php $t = $helperData->isUseFriendlyUrls(); ?>
                        <?php $block->setCategoryParent($cat) ?>
                        <?php $parentCategory = $cat->getParentCategory() ?>
                        <li data-ajax="<?php echo (int)$block->getCategoriesDataHelper()->isAjax(); ?>"
                            data-categories="1"
                            data-role="navigation-filter"
                            data-type="categories-li"
                            data-value="<?php echo $helperData->getValueCategory(
                                [
                                        'cat' => $helperData->isUseFriendlyUrls()
                                ? strtolower($cat['name']) : $cat['entity_id']
                                ]
                            ) ?>"
                            <?php if ($cat->getParentCategory()) : ?>
                                data-cat-parent = "<?php echo $cat->getParentCategory()->getId() ?>"
                            <?php else : ?>
                                data-cat-parent = "<?php echo $cat->getId() ?>"
                            <?php endif; ?>
                            data-param-cat-parent = "<?php echo 'parent_cat_'.$cat->getId(); ?>"
                            data-param="cat"
                            <?php if ($helperData->isInaCategoryRequest(
                                $helperData->isUseFriendlyUrls() ? $cat->getName(): $cat->getId(),
                                $cat
                            )
                            ) : ?>
                                data-active="1"
                            <?php endif; ?>
                            data-url="<?php echo $helperData->getUrlCategory(['cat'=>(int)$helperData
                                ->isUseFriendlyUrls() ?
                                strtolower($cat->getName()) :
                                $cat->getId(),'parent_cat_'.$cat->getId()=>$cat->getId()]) ?>">
                            <a  href="#"
                                <?php if ($helperData->isInaCategoryRequest($cat->getName(), $cat)) : ?>
                                   class="selected"
                                <?php endif; ?>>
                                <span><?php echo $block
                                        ->escapeHtml($cat->getName()) ?>(<?php echo $category->getName() ?>)</span>
                            </a>
                            <?php if ($block->getCategoriesDataHelper()->getShowAllSubcategories()
                                || $helperData->isInaCategoryRequest($helperData->isUseFriendlyUrls()
                                    ? $cat->getName(): $cat->getId(), $cat)) : ?>
                                <?php echo $block->getOlList($block->getChildCategories($cat)); ?>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
        </div>
    </div>
</div>
