<?
/**
 * @var $block \GoMage\Navigation\Block\Categories
 */
$helperData = $this->helper('GoMage\Navigation\Helper\Data');
?>

<div class="block block-gan-categories
    <?=($block->getCategoriesDataHelper()->getCategoriesNavigationType() == \GoMage\Navigation\Model\Config\Source\Navigation::DEFAULTS) ? 'gan-categories-default' : ''; ?>
    <?=($block->getCategoriesDataHelper()->getCategoriesNavigationType() == \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK) ? 'gan-categories-default gan-categories-in-block' : ''; ?>
    "
    style="background-color: <?=$block->escapeHtml($block->getNavigationViewHelper()->getNavigationViewBlockCategoriesBackgroundColor())?>"
>
    <div class="block-title gan-categories-title" data-role="navigation-filter" data-type="categories-content">
        <strong><?= __('Categories') ?></strong>
    </div>
    <div class="block-content block-content-gan-categories"<? if($block->getCategoriesDataHelper()->getCategoriesNavigationType() == \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK && $block->getCategoriesDataHelper()->getMaxBlockHeightCategories()): ?> style="max-height:<?= $block->escapeHtml($block->getCategoriesDataHelper()->getMaxBlockHeightCategories()); ?>px;"<?endif;?>>
        <div class="block-content-in"<?=($block->getCategoriesDataHelper()->isCategoriesShowCollapsed()) ? ' style="display:none;"' : '';?>>
            <ul class="gan-categories-list<?= ($block->getCategoriesDataHelper()->isShowCheckboxes()) ? ' gan-categories-list-checkbox' : '' ; ?>">
                <?
                foreach($block->getStoreCategories() as $category):
                     if (!$category->getIsActive()) continue;?>
                    <li data-ajax="<?= (int)$block->getCategoriesDataHelper()->isAjax(); ?>"
                        data-role="navigation-filter"
                        data-type="categories-li"
                        data-url="<?= $helperData->getUrlCategory(['cat'=>strtolower($category->getName())]) ?>">
                        <a href="#"<?= ($block->getCurrentCategoryId() == $category->getId()) ? ' class="selected"' : ''; ?>>
                            <span><?= $block->escapeHtml($category->getName()) ?></span>
                        </a>
                        <? if ($block->getCategoriesDataHelper()->getShowAllSubcategories() || $helperData->isInaCategoryRequest($category->getName())): ?>
                            <?= $block->getOlList($block->getChildCategories($category)); ?>
                        <? endif; ?>
                    </li>
                <? endforeach; ?>
            </ul>
        </div>
    </div>
</div>
