<?
/**
 * @var $block \GoMage\Navigation\Block\Categories
 */
?>

<div class="block block-gan-categories gan-categories-dropdown"
     style="background-color: <?=$block->escapeHtml($block->getNavigationViewHelper()->getNavigationViewBlockCategoriesBackgroundColor())?>"
>
    <div class="block-title gan-categories-title" data-role="navigation-filter" data-type="categories-content">
        <strong><?= __('Categories') ?></strong>
    </div>
    <div class="block-content block-content-gan-categories">
        <div class="gan-categories-list-dropdown block-content-in" <?=($block->getCategoriesDataHelper()->isCategoriesShowCollapsed()) ? 'style="display:none;"' : '';?>>
            <?
            foreach($block->getStoreCategories() as $category):
                if (!$category->getIsActive()) continue;?>
                    <select
                            data-role="navigation-filter"
                            data-type="categories-select"
                            data-ajax="<?= (int)$block->getCategoriesDataHelper()->isAjax(); ?>">
                        <option
                            <?= ($block->getCurrentCategoryId() == $category->getId()) ? 'selected' : ''; ?>
                                value="<?= $block->escapeUrl($block->getCategoryHelper()->getCategoryUrl($category)) ?>">
                            <?= $block->escapeHtml($category->getName()) ?>
                        </option>
                        <? if ($block->getCategoriesDataHelper()->getShowAllSubcategories()): ?>
                            <?= $block->getSelectList($block->getChildCategories($category)); ?>
                        <?endif;?>
                    </select>
            <? endforeach; ?>
        </div>
    </div>
</div>