<?php
$dataHelper = $this->helper('GoMage\Navigation\Helper\Data');
$categories = $this->getStoreCategories(true, false, true);
$categoryHelper = $this->getCategoryHelper();
?>

<div class="gan-categories gan-sidebar-position">
    <div class="gan-categories-content" data-role="navigation-filter" data-type="categories-content">CATEGORIES</div>
    <div <? echo ($dataHelper->isCategoriesShowCollapsed()) ? 'style="display:none;"' : '';?>>

            <?php
            foreach($categories as $category):
                if (!$category->getIsActive()) continue;?>
                    <select>
                        <option data-ajax="0" data-role="navigation-filter" data-type="categories-select" data-url="<?php echo $categoryHelper->getCategoryUrl($category) ?>">
                            <?php echo $category->getName() ?>
                        </option>
                        <? if(!$dataHelper->isHideEmptyCategories()) continue; ?>
                        <?// if (!$childrenCategories = $this->getChildCategories($category)) continue; ?>
                        <?foreach ($block->getChildCategories($category) as $child): ?>
                            <option data-ajax="0" data-role="navigation-filter" data-type="categories-select" data-url="<?=$child['url'] ?>">
                                <?=$child['name'] ?>
                            </option>
                        <?endforeach;?>
                    </select>
            <?php endforeach; ?>

    </div>
</div>
