<?
/**
 * @var $block \GoMage\Navigation\Block\Categories
 */
$helperData = $this->helper('GoMage\Navigation\Helper\Data');
?>

<div class="block block-gan-categories gan-categories-dropdown"
     style="background-color: <?=$block->escapeHtml($block->getNavigationViewHelper()->getNavigationViewBlockCategoriesBackgroundColor())?>"
>
    <div class="block-title gan-categories-title" data-role="navigation-filter" data-type="categories-content">
        <strong><?= __('Categories') ?></strong>
    </div>
    <div class="block-content block-content-gan-categories">
        <div class="gan-categories-list-dropdown block-content-in" <?=($block->getCategoriesDataHelper()->isCategoriesShowCollapsed()) ? 'style="display:none;"' : '';?>>
            <?
            foreach($block->getStoreCategories() as $category):
                if (!$category->getIsActive() || $block->isHidecategory($category)) continue;?>
                    <select
                            data-role="navigation-filter"
                            data-type="categories-select"
                            data-categories = "1"
                            data-select ="1"
                            data-value="<?= $helperData->getValueCategory(['cat'=>strtolower($category['name'])]) ?>"
                            data-url="<?= $helperData->getUrlCategory(['cat'=>strtolower($category->getName())]) ?>"
                            data-ajax="<?= (int)$block->getCategoriesDataHelper()->isAjax(); ?>">
                            <option
                                    data-type="remove-item"
                                    data-value=""
                                    data-param-to-remove="cat"
                                    value=""
                            ><?php echo __('Choose Category')?></option>
                        <option
                            data-value="<?= $helperData->getValueCategory(['cat'=>strtolower($category['name'])]) ?>"
                            data-param="cat"
                            <?php if ($helperData->isInaCategoryRequest($category->getName())) : ?>
                                data-active="1"
                            <?php endif; ?>
                            <?php if ($helperData->isInaCategoryRequest($category->getName())) : ?>
                                class="selected"
                            <?php endif; ?>
                                value="<?= $helperData->getValueCategory(['cat'=>strtolower($category['name'])]) ?>">
                            <?= $block->escapeHtml($category->getName()) ?>
                        </option>
                        <? if ($block->getCategoriesDataHelper()->getShowAllSubcategories() || $helperData->isInaCategoryRequest($category->getName())): ?>
                            <?= $block->getSelectList($block->getChildCategories($category)); ?>
                        <?endif;?>
                    </select>
            <? endforeach; ?>
        </div>
    </div>
</div>