<div class="block block-gan-categories gan-sidebar-position gan-categories-flyout"
     style="background-color: <?=$block->getDataHelper()->getNavigationViewBlockCategoriesBackgroundColor()?>"
>
    <div class="block-title gan-categories-title" data-role="navigation-filter" data-type="categories-content">
        <strong><?php echo __('Categories') ?></strong>
    </div>
    <div class="block-content block-content-gan-categories">
        <div class="block-content-in"<? echo ($block->getCategoriesDataHelper()->isCategoriesShowCollapsed()) ? ' style="display:none;"' : '';?>>
            <ul class="gan-categories-list">
                <?php
                foreach($block->getStoreCategories(true, false, true) as $category):
                     if (!$category->getIsActive()) continue;?>
                    <li
                            data-ajax="<?= (int)$block->getCategoriesDataHelper()->isAjax(); ?>"
                            data-role="navigation-filter"
                            data-type="categories-li"
                            data-url="<?= $block->getCategoryHelper()->getCategoryUrl($category) ?>">
                        <a href="#"<?= ($block->getCurrentCategoryId() == $category->getId()) ? ' class="selected"' : ''; ?>>
                            <?= $category->getName() ?>
                        </a>
                        <?= $block->getOlList($block->getChildCategories($category)); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
