<?php
/**
 * @var $block \GoMage\Navigation\Block\Categories
 */
$helperData = $this->helper('GoMage\Navigation\Helper\Data');
?>

<div class="block block-gan-categories gan-categories-flyout"
     style="background-color: <?=$block->escapeHtml($block->getNavigationViewHelper()->getNavigationViewBlockCategoriesBackgroundColor())?>"
>
    <div class="block-title gan-categories-title" data-role="navigation-filter" data-type="categories-content">
        <strong><?= __('Categories') ?></strong>
    </div>
    <div class="block-content block-content-gan-categories">
        <div class="block-content-in" <?= ($block->getCategoriesDataHelper()->isCategoriesShowCollapsed()) ? 'style="display:none;"' : '';?>>
            <ul class="gan-categories-list">
                <?php
                foreach($block->getStoreCategories() as $category):
                    if (!$category->getIsActive() || $block->isHidecategory($category)) continue;?>
                    <li
                            data-ajax="<?= (int)$block->getCategoriesDataHelper()->isAjax(); ?>"
                            data-categories = "1"
                            data-value="<?= $helperData->getValueCategory(['cat'=>$helperData->isUseFriendlyUrls() ? strtolower($category->getName()): $category->getId()]) ?>"
                            data-param="cat"
                        <?php if ($helperData->isInaCategoryRequest($helperData->isUseFriendlyUrls() ? $category->getName(): $category->getId(), $category)) : ?>
                            data-active="1"
                        <?php endif; ?>
                            data-role="navigation-filter"
                            data-type="categories-li"
                            data-url="<?= $helperData->getUrlCategory(['cat'=>$helperData->isUseFriendlyUrls() ? strtolower($category->getName()): $category->getId()]) ?>">
                        <a href="#"<?php if ($helperData->isInaCategoryRequest($helperData->isUseFriendlyUrls() ? $category->getName(): $category->getId())) : ?>
                            class="selected"
                        <?php endif; ?>>
                            <?= $block->escapeHtml($category->getName()) ?>
                        </a>
                    <?php if ($block->getCategoriesDataHelper()->getShowAllSubcategories() || $helperData->isInaCategoryRequest($helperData->isUseFriendlyUrls() ? $category->getName(): $category->getId())): ?>
                        <?= $block->getOlList($block->getChildCategories($category)); ?>
                    <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
