<?php
$dataHelper = $this->helper('GoMage\Navigation\Helper\Data');
$categories = $this->getStoreCategories(true, false, true);
$categoryHelper = $this->getCategoryHelper();
$dataHelper->isShowCheckboxes();
?>
<div class="block block-gan-categories gan-sidebar-position gan-categories-flyout">
    <div class="block-title gan-categories-title" data-role="navigation-filter" data-type="categories-content">
        <strong><?php echo __('Categories') ?></strong>
    </div>
    <div class="block-content block-content-gan-categories">
        <div <? echo ($dataHelper->isCategoriesShowCollapsed()) ? 'style="display:none;"' : '';?>>
            <ul class="gan-categories-list" <?= ($dataHelper->isShowCheckboxes()) ? :''; ?>>
                <?php
                foreach($categories as $category):
                     if (!$category->getIsActive()) continue;?>
                    <li data-ajax="<?= (int)$dataHelper->isAjax(); ?>" data-role="navigation-filter" data-type="categories-li" data-url="<?= $categoryHelper->getCategoryUrl($category) ?>">
                        <a class="<?= ($block->getCurrentCategoryId() == $category->getId()) ? 'active' : ''; ?>"
                           href="#"> <?= $category->getName() ?></a>
                    </li>
                    <?= $block->getOlList($block->getChildCategories($category)); ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
