<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 1.1.0
 * @since     Class available since Release 1.0.0
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="gan-to-top-button">
    <button id="gan-to-top-button-gomage"
            data-role="navigation-filter"
            data-type="back-to-top"
    ><span><?php echo __('Back To Top') ?></span></button>
</div>
