<div id="advanced-navigation-template" data-bind="scope:'advancedNavigation'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                   "advancedNavigation": {
                        "component": "GoMage_Navigation/js/advancedNavigation"
                    },
                    "advancedNavigationDataModel": {
                        "component": "GoMage_Navigation/js/dataModel"
                    }
               }
            }
        }
    }

    </script>
</div>
<div id="advanced-navigation-products-template" data-bind="scope:'advancedNavigationProducts'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "advancedNavigationProducts": {
                        "component": "GoMage_Navigation/js/advancedNavigationProducts"
                    }
               }
            }
        }
    }

    </script>
</div>