<?php
/**
 * @var $block \GoMage\Navigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
<div class="filter-current active">
    <strong class="block-subtitle filter-current-subtitle"
            role="heading"
            aria-level="2"
            data-count="<?=(int)count($_filters); ?>"><?= __('Applied Filters:') ?></strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter): ?>
            <li class="item">
                <span class="filter-label"><?=$block->escapeHtml(__($_filter->getName())); ?></span>
                <div class="filter-value-wrap">
                    <span class="filter-value"><?= $block->escapeHtml($_filter->getLabel(), ['span']) ?></span>
                    <?php $currentFilterName = $block->escapeHtml(__($_filter->getName()) . " " . $_filter->getLabel()); ?>
                    <a class="action remove"
                       href="#"
                       title="<?= $block->escapeHtml(__('Remove') . " " . $currentFilterName);?>"
                       data-role="navigation-filter"
                       data-value="<?=$block->escapeHtmlAttr($_filter->getRemoveValue()) ?>"
                       data-url="<?= $block->escapeHtmlAttr($_filter->getRemoveUrl()) ?>"
                       data-param="<?=$block->escapeHtmlAttr($_filter->getFilter()->getRequestVar()) ?>"
                        <?if ($_filter->getFilter()->getGomageIsAjax() || is_null($_filter->getFilter()->getGomageIsAjax())):?>
                            data-ajax="1"
                        <?else:?>
                            data-ajax="0"
                        <?endif;?>
                       data-type="remove-item"
                       data-active="1">
                        <span><?= __('Remove This Item') ?></span>
                    </a>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
