<?php
/**
 * @var $block \GoMage\Navigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
<div class="filter-current active">
    <strong class="block-subtitle filter-current-subtitle"
            role="heading"
            aria-level="2"
            data-count="<?php echo count($_filters); ?>"><?php /* @escapeNotVerified */ echo __('Applied Filters:') ?></strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter): ?>
            <li class="item">
                <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
                <div class="filter-value-wrap">
                    <span class="filter-value"><?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?></span>
                    <?php $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel()); ?>
                    <a class="action remove"
                       href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>"
                       data-role="navigation-filter"
                       data-value="<?php echo $_filter->getValueString() ?>"
                       data-param="<?php echo $_filter->getRequestVar() ?>"
                       data-ajax="<?php echo $_filter->getFilter()->getData('gomage_is_ajax'); ?>"
                       data-active="1">
                        <span><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
                    </a>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
