<?php $helperViewData = $this->helper('GoMage\Navigation\Helper\NavigationViewData') ?>
<?php
/**
 * @var GoMage\Navigation\Helper\Data $helperData
 */
      $helperData = $this->helper(GoMage\Navigation\Helper\Data::class);
      $asset = $helperData->getAssets();
?>
<?php if($helperData->isEnable()): ?>
<link rel="stylesheet" type="text/css" href="<?php echo $asset->createAsset('GoMage_Navigation::css/gomage-navigation.css')->getUrl(); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $asset->createAsset('GoMage_Navigation::css/jslider.blue.css')->getUrl(); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $asset->createAsset('GoMage_Navigation::css/jslider.css')->getUrl(); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $asset->createAsset('GoMage_Navigation::css/jslider.plastic.css')->getUrl(); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $asset->createAsset('GoMage_Navigation::css/jslider.round.css')->getUrl(); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $asset->createAsset('GoMage_Navigation::css/jslider.round.plastic.css')->getUrl(); ?>">
<style type="text/css">
    .page-layout-1column .toolbar.toolbar-products {
        position: static;
    }
    <?php if ($helperViewData->getNavigationViewSliderLineHeight() < $helperViewData->getNavigationViewSliderElementHeight()):?>
    .gan-filter-slider .layout {
        padding-bottom: <?=$block->escapeHtml($helperViewData->getNavigationViewSliderElementHeight())?>px;
        margin-left: <?=$block->escapeHtml(($helperViewData->getNavigationViewSliderElementWidth() / 2))?>px;
        margin-right: <?=$block->escapeHtml(($helperViewData->getNavigationViewSliderElementWidth() / 2))?>px;
    }

    .gan-filter-slider .jslider .jslider-label,
    .gan-filter-slider .jslider .jslider-value {
        margin-top: <?= $block->escapeHtml((($helperViewData->getNavigationViewSliderElementHeight() - $helperViewData->getNavigationViewSliderLineHeight()) / 2 + 10)) ?>px;
    }

    <?php endif;?>

    .gan-filter-slider .jslider .jslider-bg,
    .gan-filter-slider .jslider .jslider-bg .f,
    .gan-filter-slider .jslider .jslider-bg .r,
    .gan-filter-slider .jslider .jslider-bg .l,
    .gan-filter-slider .jslider .jslider-bg .v {

        /* Slider Line Height */
        height: <?=$block->escapeHtml($helperViewData->getNavigationViewSliderLineHeight())?>px;

    }

    .gan-filter-slider .jslider .jslider-bg .v {

        /* Slider Line Color */
        background: <?=$block->escapeHtml($helperViewData->getNavigationViewSliderLineColor())?>;

    }

    .gan-filter-slider .jslider_round_plastic .jslider-pointer {

        /* Slider Element Color */
        background: <?=$block->escapeHtml($helperViewData->getNavigationViewSliderElementColor())?>;

        /* Slider Element Width */
        width: <?=$block->escapeHtml($helperViewData->getNavigationViewSliderElementWidth())?>px;

        /* Slider Element Height */
        height: <?=$block->escapeHtml($helperViewData->getNavigationViewSliderElementHeight())?>px;

        /* Slider Element Radius */
        border-radius: <?=$block->escapeHtml($helperViewData->getNavigationViewSliderElementRadius())?>px;

    }
</style>

<?php endif; ?>