<? if($filter->getGomageIsShowTooltip()):?>

    <? $test = $block->getHelper()->isNavigationViewTooltipShowOnClick(); ?>
    <? $test = $block->getHelper()->isNavigationViewTooltipShowOnMouseOver(); ?>
    <? $test = $block->getHelper()->isNavigationViewTooltipHideOnMouseOut(); ?>
    <? $test = $block->getHelper()->isNavigationViewTooltipHideOnCloseButton(); ?>

    <div>
        tooltip
        <div style="display: none; width: <?=$filter->getGomageTooltipWidth();?>px; height: <?=$filter->getGomageTooltipHeight();?>px;">
            <?=$block->getTooltipText($filter->getGomageTooltipText());?>
        </div>
    </div>
<?endif;?>