<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 *
 * @var $block \GoMage\Navigation\Block\Navigation
 */

?>

<?$block->getContainerClass();?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter block-gan-filter gan-sidebar-position" data-role="navigation" data-mage-init='{"navigation": {
                        "addFilterResultsToUrl": "<?php echo $block->getDataHelper()->isAddFilterResultsToUrl()?>",
                        "navigationPlace": "<?php echo $block->getDataHelper()->getShowShopByIn(); ?>",
                        "categoriesPlace": "<?php echo $block->getCategoryDataHelper()->getCategoriesBlockLocation(); ?>",
                        "backToTopSpeed": "<?php echo $block->getDataHelper()->getBackToTopSpeed(); ?>",
                        "backToTopAction": "<?php echo $block->getDataHelper()->getBackToTopAction(); ?>",
                        "ajaxAutoload": "<?php echo $block->getDataHelper()->isUseAutoScrolling(); ?>"
                        }}' style="background-color: <?=$block->getNavigationViewHelper()->getNavigationViewBlockBackgroundColor()?>; ">
        <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Add Filter') ?></strong></div>
        <div class="block-content filter-content">
            <?if ($block->getDataHelper()->isShowAppliedValuesInResults()):?>
                <?php echo $block->getStateBlock()->toHtml() ?>
                <?php if ($block->getLayer()->getState()->getFilters()): ?>
                    <div class="block-actions filter-actions">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>"
                           class="action clear filter-clear"
                           data-role="navigation-filter"
                           data-ajax="1"
                           data-clear="1">
                            <span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span>
                        </a>
                    </div>
                <?php endif; ?>
            <?php endif;?>
            <?php $wrapOptions = false; ?>

                <?php foreach ($block->getFilters() as $filter): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                        <dl class="filter-options"
                            id="narrow-by-list"
                            data-role="content"
                            data-mage-init='{"accordion":{
                            "openedState": "active",
                            "collapsible": true,
                            "active": <?php echo json_encode($block->getExpandedFilters());?>,
                            "multipleCollapsible": true
                            }}'>
                        <?if(!empty($block->getCategoriesHtml())):?>
                            <div data-role="collapsible" class="filter-options-item <?= $block->getItemClass() ?>"
                                 style="<?= $block->getItemWidthStyle() ?>">
                                <dt data-role="title" role="heading" aria-level="3" class="filter-options-title"><?php echo 'Categories'; ?></dt>
                                <dd data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getCategoriesHtml(); ?></dd>
                            </div>
                        <?endif;?>

                        <?php $wrapOptions = true; endif; ?>

                        <?php if ($filter->getItemsCount()): ?>
                            <div data-role="collapsible" class="filter-options-item <?= $block->getItemClass() ?>"
                                 style="<?= $block->getItemWidthStyle() ?>">
                                <dt data-role="title" role="heading" aria-level="3" class="filter-options-title"><?php echo $block->escapeHtml(__($filter->getName())) ?></dt>
                                <dd data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getRenderBlock()->render($filter); ?></dd>
                            </div>
                        <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
                    </dl>
                <?php endif; ?>

        </div>
    </div>
<?php endif; ?>
