<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 *
 * @var $block \GoMage\Navigation\Block\Navigation
 */

?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter block-gan-filter <?=$block->escapeHtmlAttr($block->getContainerClass());?>" data-role="navigation" data-mage-init='{"navigation": {
                        "addFilterResultsToUrl": "<?= $block->escapeHtmlAttr($block->getDataHelper()->isAddFilterResultsToUrl())?>",
                        "navigationPlace": "<?= $block->escapeHtmlAttr($block->getDataHelper()->getShowShopByIn()); ?>",
                        "categoriesPlace": "<?= $block->escapeHtmlAttr($block->getCategoryDataHelper()->getCategoriesBlockLocation()); ?>",
                        "backToTopSpeed": "<?= $block->escapeHtmlAttr($block->getDataHelper()->getBackToTopSpeed()); ?>",
                        "backToTopAction": "<?= $block->escapeHtmlAttr($block->getDataHelper()->getBackToTopAction()); ?>",
                        "ajaxAutoload": "<?= $block->escapeHtmlAttr($block->getDataHelper()->isUseAutoScrolling()); ?>"
                        }}' style="background-color: <?=$block->getNavigationViewHelper()->getNavigationViewBlockBackgroundColor()?>; ">
        <div class="block-title"><strong><?= __('Add Filter') ?></strong></div>
        <div class="block-content filter-content">
            <?if ($block->getDataHelper()->isShowAppliedValuesInResults()):?>
                <?= $block->getStateBlock()->toHtml() ?>
                <?php if ($block->getLayer()->getState()->getFilters()): ?>
                    <div class="block-actions filter-actions">
                        <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
                           class="action clear filter-clear"
                           data-role="navigation-filter"
                           data-ajax="1"
                           data-clear="1">
                            <span><?= __('Clear All') ?></span>
                        </a>
                    </div>
                <?php endif; ?>
            <?php endif;?>
            <?php $wrapOptions = false; ?>

                <?php foreach ($block->getFilters() as $filter): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= __('Shopping Options') ?></strong>
                        <dl class="filter-options"
                            id="narrow-by-list"
                            data-role="content"
                            data-mage-init='{"accordion":{
                            "openedState": "active",
                            "collapsible": true,
                            "active": <?= json_encode($block->getExpandedFilters());?>,
                            "multipleCollapsible": true
                            }}'>

                        <?php $wrapOptions = true; endif; ?>

                        <?php if ($filter->getItemsCount()): ?>
                            <div data-role="collapsible" class="filter-options-item <?= $block->escapeHtmlAttr($block->getItemClass()) ?>"
                                 style="<?= $block->escapeHtmlAttr($block->getItemWidthStyle()) ?>">
                                <dt data-role="title" role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></dt>
                                <dd data-role="content" class="filter-options-content"><?= $block->getRenderBlock()->render($filter); ?></dd>
                            </div>
                        <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
                    </dl>
                <?php endif; ?>

        </div>
    </div>
<?php endif; ?>
