<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 2.0.0
 * @since     Class available since Release 2.0.0
 */

$helper = $this->helper('GoMage\Navigation\Helper\Data');
$moreButton = $this->getLayout()->createBlock('GoMage\Navigation\Block\Product\ProductList\More');
?>

<?php if ($block->getCollection()->getSize()) : ?>

    <?php if ($block->getUseContainer()) : ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()) : ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1) : ?>
                <?php echo $block->escapeHtml(__('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum())) ?>
            <?php elseif ($block->getTotalNum() == 1) : ?>
                <?php echo $block->escapeHtml(__('%1 Item', $block->getTotalNum())) ?>
            <?php else: ?>
                <?php echo $block->escapeHtml(__('%1 Item(s)', $block->getTotalNum())) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>
        <?php if ($block->getLastPageNum() > 1) : ?>
        <div class="pages" <?php if (!$helper->isShowPager() || $helper->isUseAutoScrolling()) : ?>style="display: none"<?php 
       endif; ?>>
            <strong class="label pages-label" id="paging-label"><?php echo __('Page') ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
            <?php if (!$block->isFirstPage()) : ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?php echo $text ? 'link ' : 'action '?> previous"
                       href="<?php echo $block->escapeUrl($block->getPreviousPageUrl()) ?>"
                       title="<?php echo $text ? $text : __('Previous') ?>"
                       data-role="navigation-filter"
                       data-value="<?php echo $block->escapeHtml($block->getCollection()->getCurPage(-1)) ?>"
                       data-param="<?php echo $block->escapeHtml($block->getPageVarName()) ?>"
                       data-ajax="1"
                       data-active="">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span><?php echo $block->escapeHtml($text ? $text : __('Previous')) ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()) : ?>
                <li class="item">
                    <a class="page first" href="<?php echo $block->escapeUrl($block->getFirstPageUrl()) ?>"
                       data-role="navigation-filter"
                       data-value="1"
                       data-param="<?php echo $block->escapeHtml($block->getPageVarName()) ?>"
                       data-ajax="1"
                       data-active="">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()) : ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?php echo $block
                        ->escapeUrl($block->getPreviousJumpUrl()) ?>"
                       data-role="navigation-filter"
                       data-value="<?php echo $block->escapeUrl($block->getPreviousJumpPage()) ?>"
                       data-param="<?php echo $block->escapeUrl($block->getPageVarName()) ?>"
                       data-ajax="1"
                       data-active="">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page)) : ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?php echo __('You\'re currently reading page') ?></span>
                            <span><?php echo $block->escapeHtml($_page) ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?php echo $block->escapeUrl($block->getPageUrl($_page)) ?>" class="page"
                           data-role="navigation-filter"
                           data-value="<?php echo $block->escapeHtml($_page) ?>"
                           data-param="<?php echo $block->escapeHtml($block->getPageVarName()) ?>"
                           data-ajax="1"
                           data-active="">
                            <span class="label"><?php echo __('Page') ?></span>
                            <span><?php echo $block->escapeHtml($_page) ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()) : ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?php echo $block->escapeUrl($block->getNextJumpUrl()) ?>"
                       data-role="navigation-filter"
                       data-value="<?php echo $block->escapeHtml($block->getNextJumpPage()) ?>"
                       data-param="<?php echo $block->escapeHtml($block->getPageVarName()) ?>"
                       data-ajax="1"
                       data-active="">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()) : ?>
              <li class="item">
                  <a class="page last" href="<?php echo $block->escapeUrl($block->getLastPageUrl()) ?>"
                     data-role="navigation-filter"
                     data-value="<?php echo $block->escapeHtml($block->getCollection()->getLastPageNumber()) ?>"
                     data-param="<?php echo $block->escapeHtml($block->getPageVarName()) ?>"
                     data-ajax="1"
                     data-active="">
                      <span class="label"><?php echo __('Page') ?></span>
                      <span><?php echo $block->escapeHtml($block->getLastPageNum()) ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()) : ?>
                <li class="item pages-item-next gomage-pager_navigation">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?php echo $text ? 'link ' : 'action '?> next"
                       href="<?php echo $block->escapeUrl($block->getNextPageUrl()) ?>"
                       title="<?php echo $block->escapeHtml($text ? $text : __('Next')) ?>"
                       data-role="navigation-filter"
                       data-value="<?php echo $block->escapeHtml($block->getCollection()->getCurPage(+1)) ?>"
                       data-param="<?php echo $block->escapeHtml($block->getPageVarName()) ?>"
                       data-ajax="1"
                       data-active="">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span><?php echo $block->escapeHtml($text ? $text : __('Next')) ?></span>
                    </a>
                </li>
            <?php endif;?>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()) : ?>
        <div class="limiter">
            <strong class="limiter-label"><?php echo __('Show') ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options" data-role="navigation-filter" data-type="select" data-param="product_list_limit" >
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?php echo $block->escapeHtml(($block->getLimitUrl($_key))) ?>"<?php if ($block->isLimitCurrent($_key)) : ?>
selected="selected"<?php endif ?>>
                        <?php echo $block->escapeHtml($_limit) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?php echo __('per page') ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()) : ?>
    </div>
    <?php endif ?>

<?php endif ?>
