<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 1.0.0
 * @since     Class available since Release 1.0.0
 */

// @codingStandardsIgnoreFile

?>
<?php
$helper = $this->helper('GoMage\Navigation\Helper\Data');
?>
<?php if ($helper->isShowValueQty()): ?>
    <p class="toolbar-amount gan-toolbar-amount" id="toolbar-amount"
       data-last-number = "<?php echo $block->getLastNum() ?>"
       data-total-number = "<?php echo $block->getTotalNum() ?>"
       data-limit-number = "<?php echo $block->getLimit() ?>"
    >
        <?php if ($block->getLastPageNum() > 1): ?>
            <?= __('Items %1-%2 of %3',
                '<span class="toolbar-number">' . (int) $block->getFirstNum() . '</span>',
                '<span class="toolbar-number gan-last-number">' . (int) $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php elseif ($block->getTotalNum() == 1): ?>
            <?= __('%1 Item',
               '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php else: ?>
            <?= __('%1 Items',
                '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php endif; ?>
    </p>
<?php endif;?>