<?php

// @codingStandardsIgnoreFile

?>
<?php
$helper = $this->helper('GoMage\Navigation\Helper\Data');
?>
<?php if ($helper->isShowValueQty()): ?>
    <p class="toolbar-amount gan-toolbar-amount" id="toolbar-amount"
       data-last-number = "<?php echo $block->getLastNum() ?>"
       data-total-number = "<?php echo $block->getTotalNum() ?>"
       data-limit-number = "<?php echo $block->getLimit() ?>"
    >
        <?php if ($block->getLastPageNum() > 1): ?>
            <?= __('Items %1-%2 of %3',
                '<span class="toolbar-number">' . (int) $block->getFirstNum() . '</span>',
                '<span class="toolbar-number gan-last-number">' . (int) $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php elseif ($block->getTotalNum() == 1): ?>
            <?= __('%1 Item',
               '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php else: ?>
            <?= __('%1 Items',
                '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php endif; ?>
    </p>
<?php endif;?>