<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
$helper = $this->helper('GoMage\Navigation\Helper\Data');
?>
<?php if ($helper->isShowValueQty()): ?>
    <p class="toolbar-amount" id="toolbar-amount">
        <?php if ($block->getLastPageNum() > 1): ?>
            <?= __('Items %1-%2 of %3',
                '<span class="toolbar-number">' . (int) $block->getFirstNum() . '</span>',
                '<span class="toolbar-number">' . (int) $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php elseif ($block->getTotalNum() == 1): ?>
            <?= __('%1 Item',
               '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php else: ?>
            <?= __('%1 Items',
                '<span class="toolbar-number">' . (int) $block->getTotalNum() . '</span>') ?>
        <?php endif; ?>
    </p>
<?endif;?>