<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 1.1.0
 * @since     Class available since Release 1.0.0
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

/**
 * @var \GoMage\Navigation\Helper\Data $helper
 */
$helper = $this->helper('GoMage\Navigation\Helper\Data');
?>
<div class="field limiter">
    <label class="label" for="limiter">
        <span><?= /* @escapeNotVerified */ __('Show') ?></span>
    </label>
    <div class="control">
        <select id="limiter"
                class="limiter-options" data-role="navigation-filter"
                data-type="select" data-param="product_list_limit"
                <?php if($helper->isPaginationAjax()): ?>data-ajax="1" <?php endif; ?>
                data-active="1">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <option value="<?= $block->escapeHtml($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                    selected="selected"<?php endif ?>>
                    <?= $block->escapeHtml($_limit) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <span class="limiter-text"><?= /* @escapeNotVerified */ __('per page') ?></span>
</div>
