<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 1.0.0
 * @since     Class available since Release 1.0.0
 */

/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

/**
 * @var \GoMage\Navigation\Helper\Data $helper
 */
$helper = $this->helper('GoMage\Navigation\Helper\Data');
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php echo __('Sort By') ?></label>
    <select id="sorter" data-role="navigation-filter"
            data-param="product_list_order"
            <?php if ($helper->isPaginationAjax()) : ?>
                data-ajax="1"
        <?php endif; ?>
            data-active="1" class="sorter-options"
            data-type="select">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) : ?>
            <option value="<?php echo $block->escapeHtml($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) : ?>
                    selected="selected"
                <?php endif; ?>
            >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') : ?>
        <a title="<?php echo __('Set Ascending Direction') ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="navigation-filter"
           data-param="product_list_dir"
           data-value="asc"
            <?php if ($helper->isPaginationAjax()) : ?>
               data-ajax="1"
            <?php endif; ?>>
            <span><?php echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else : ?>
        <a title="<?php echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc"
           data-role="navigation-filter" data-param="product_list_dir" data-value="desc"
            <?php if ($helper->isPaginationAjax()) : ?>
                data-ajax="1"
            <?php endif; ?>>
            <span><?php echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
