<?php
/**
 *
 * @var $block \Gomage\Navigation\Block\Navigation\FilterRenderer
 */

$filter = reset($filterItems)->getFilter();
$filter->getGomageFilterType();
$filter->getGomageIsShowFilterButton();
$filter->getGomageMaxBlockHeight();
$filter->getGomageIsAjax();
$filter->getGomageIsCollapsed();
$filter->getGomageIsCheckbox();
$filter->getGomageIsShowImageName();
$filter->getGomageOptionsAlignment();
$filter->getGomageImageWidth();
$filter->getGomageImageHeight();
$filter->getGomageVisibleOptions();
$filter->getGomageIsShowTooltip();
$filter->getGomageTooltipWidth();
$filter->getGomageTooltipHeight();
$filter->getGomageIsReset();
$filter->getGomageIsExcludeCategories();

?>
<ol class="items gan-filter gan-filter-default <?php if($filter->getGomageFilterType() == \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK) echo 'gan-filter-in-block'; ?> <?php echo $filter->canShowMinimized() ? "filter-content-hide" : "filter-content-show"; ?>">

    <?php foreach ($filterItems as $item): ?>
        <li class="item">
            <?php if ($item->getCount() > 0): ?>
                <a <?php if(!$item->getIsActive()):?> href="<?php echo $item->getGomageUrl(); ?> <?endif;?>"
                    <?php if($item->getIsActive()):?>
                        class="active"
                    <?endif;?>
                   data-role="navigation-filter"
                   data-url="<?php if(!$item->getIsActive()):?><?php echo $item->getGomageUrl(); ?> <?endif;?>"
                   data-value="<?php echo $item->getValueString() ?>"
                   data-param="<?php echo $filter->getRequestVar() ?>"
                   data-ajax="<?php echo $filter->getGomageIsAjax(); ?>"
                   data-type="<?php echo (int) $filter->getGomageFilterType(); ?>"
                   <?php if($item->getIsActive()):?>
                    data-active="1">
                    <?php endif;?>
                    <span class="filter-label-text"><?php echo $item->getLabel() ?></span>
                    <?php if ($item->getIsPreferred()) : ?><div class="filter-preferred"><?php echo __('Preferred brand') ?></div><?php endif?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $item->getCount()?><span class="filter-count-label">
                            <?php if ($item->getCount() == 1):?> <?php echo __('item')?><?php else:?> <?php echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php echo $item->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php echo $item->getCount()?><span class="filter-count-label">
                        <?php if ($item->getCount() == 1):?><?php echo __('item')?><?php else:?><?php echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
