<?php
/**
 *
 * @var $block \GoMage\Navigation\Block\Navigation\FilterRenderer
 */

$filter = reset($filterItems)->getFilter();
$filter->getGoMageFilterType();
$filter->getGoMageIsShowFilterButton();
$filter->getGoMageMaxBlockHeight();
$filter->getGoMageIsAjax();
$filter->getGoMageIsCollapsed();
$filter->getGoMageIsCheckbox();
$filter->getGoMageIsShowImageName();
$filter->getGoMageOptionsAlignment();
$filter->getGoMageImageWidth();
$filter->getGoMageImageHeight();
$filter->getGoMageVisibleOptions();
$filter->getGoMageIsShowTooltip();
$filter->getGoMageTooltipWidth();
$filter->getGoMageTooltipHeight();
$filter->getGoMageIsReset();
$filter->getGoMageIsExcludeCategories();

?>

<div class="gan-filter gan-filter-dropdown">
    <select data-role="navigation-filter"
            data-param="<?php echo $filter->getRequestVar() ?>"
            data-type="select"
            <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                data-ajax="1"
            <?else:?>
                data-ajax="0"
            <?endif;?>
            <?php if (!empty($filter->getUsedOptions())): ?>
                data-active="1"
            <? endif; ?>
    >
        <option value=""><?php echo __('Select Filter') ?></option>
        <?php foreach ($filterItems as $item): ?>
            <?php if ($item->getCount() > 0 && $item->isShowAppliedValues()): ?>
                <option value="<?php echo $item->getValueString() ?>"
                        <?php if ($item->getIsActive()): ?>selected="selected" data-active="1"<?php endif ?>>
                    <?php echo $item->getLabel() . ' (' . $item->getCount() . ')' ?>
                </option>
            <?php endif; ?>
        <?php endforeach ?>
    </select>
</div>
