<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \GoMage\Navigation\Block\Navigation\FilterRenderer
 */
?>

<ol class="items">
    <?php $filterItem = reset($filterItems) ?>
    <select data-role="navigation-filter"
            data-param="<?php echo $filterItem->getRequestVar() ?>"
            data-type="<?php echo $block->getType(); ?>"
            data-ajax="<?php echo $filterItem->getFilter()->getData('gomage_is_ajax'); ?>">
        <option><?php echo __('Select Filter') ?></option>
        <?php foreach ($filterItems as $filterItem): ?>
            <?php if ($filterItem->getCount() > 0): ?>
                <option value="<?php echo $filterItem->getValueString() ?>"
                        <?php /*if ($filterItem->isActive()): */?><!--selected="selected"--><?php /*endif */?>
                        <!--data-active="<?php /*echo $filterItem->isActive() */?>">-->
                    <?php echo $filterItem->getLabel() ?>
                </option>
            <?php endif; ?>
        <?php endforeach ?>
    </select>
</ol>
