<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 1.0.0
 * @since     Class available since Release 1.0.0
 */

/**
 *
 * @var $block \Gomage\Navigation\Block\Navigation\FilterRenderer
 */

$filter = reset($filterItems)->getFilter();
$optionsLimit = ($filter->getGomageVisibleOptions()) ? $filter->getGomageVisibleOptions() : false;
$cnt = 0;
$helperData = $this->helper('GoMage\Navigation\Helper\Data');
$categoriesHelper = $this->helper('GoMage\Navigation\Helper\CategoryData');
$categoriesHelperImage = $this->helper('GoMage\Navigation\Helper\ImageSwatchHelper');
?>
<ol class="items gan-filter gan-filter-default
<?php if ($filter->getGomageIsCheckbox() || ($filter->isCategoryFilter() && ($categoriesHelper->isShowCheckboxes()))) :
    ?> gan-filter-checkbox
            <?php endif; ?>
<?php echo ($categoriesHelper->getCategoriesImageAlignment()) ?
    ' gan-categories-list-alignment-' . $categoriesHelper->getCategoriesImageAlignment().' ' : ''; ?>
<?php echo $helperData->getOptionsAlignment((int)$filter->getGomageOptionsAlignment()); ?>

<?php if ($filter->getGomageFilterType() == \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK) {
    echo ' gan-filter-in-block';
} ?>
<?php
if ($filter->getGomageIsCheckbox()) :
        ?> gan-filter-checkbox
<?php endif; ?>"
    <?php if ($filter->getGomageFilterType() == \GoMage\Navigation\Model\Config\Source\Navigation::IN_BLOCK && $filter
            ->getGomageMaxBlockHeight()) : ?>
        <?php if ($filter->isCategoryFilter() && $categoriesHelper->getMaxBlockHeightCategories()) : ?>
            style="max-height:<?php echo $block->escapeHtml($filter->getGomageMaxBlockHeight()); ?>px;"
        <?php endif; ?>
    <?php endif; ?>>
    <?php $optionsLimit = ($filter->getGomageVisibleOptions()) ? $filter->getGomageVisibleOptions() : false;
    $cnt = 0;
    ?>
    <?php foreach ($filterItems as $item) : ?>
        <li class="item <?php echo (!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element' : '' ?>"
            style="<?php echo ((!empty(($optionsLimit) && $cnt >= $optionsLimit)) ||
                (!empty(($optionsLimit) && $cnt >= $optionsLimit) && !$helperData
                        ->isShowMore($filter->getName()))) ? 'display:none' : '' ?>">
            <?php if ($item->getCount() > 0 || ($helperData->isShowEmptyCategory() && $filter->isCategoryFilter())) : ?>
                <a <?php if (!$item->getIsActive()) : ?>
                        href="<?php echo $block->escapeUrl($item->getGomageUrl()); ?> <?php
                        endif;
                        ?>"
                    <?php if ($item->getIsActive()) : ?>
                        class="active"
                    <?php endif; ?>
                        data-role="navigation-filter"
                        data-url="<?php
                        if (!$item->getIsActive()) : ?>

                    <?php
                            echo $block->escapeUrl($item->getGomageUrl())
                            ?> <?php
                        endif; ?>"
                        data-value="<?php echo $block->escapeHtml($item->getGomageValue()) ?>"
                        data-param="<?php echo $block->escapeHtml($filter->getRequestVar()) ?>"
                    <?php if (($filter->getGomageIsAjax() || null === ($filter->getGomageIsAjax()))
                        && (($filter->isCategoryFilter() && $categoriesHelper->isAjax()) ||
                            !$filter->isCategoryFilter())) : ?>
                        data-ajax="1"
                    <?php else : ?>
                        data-ajax="0"
                    <?php endif; ?>
                        data-type="<?php echo (int)$filter->getGomageFilterType(); ?>"
                    <?php if ($item->getIsActive()) : ?>
                        data-active="1"
                    <?php endif; ?>
                        <?php
                        if ((!$item->isShowAppliedValues())) :
                        ?>style="display: none"<?php
                        endif; ?>>
                    <?php if ($filter->getImageCategory($item->getValue())) : ?>
                        <img src="<?php echo $categoriesHelper->resize($filter->getImageFile($item->getValue())) ?>"
                             width="<?php echo ($categoriesHelper->getCategoriesImageWidth()) ?
                                 $block->escapeHtml($categoriesHelper->getCategoriesImageWidth()) . 'px' : ''; ?>"
                             height="<?php echo ($categoriesHelper->getCategoriesImageHeight()) ?
                                 $block->escapeHtml($categoriesHelper->getCategoriesImageHeight()) . 'px' : ''; ?>"
                        >
                    <?php endif; ?>

                    <?php if ($categoriesHelper->isShowImageName()) : ?>
                        <span class="filter-label-wrap">
                            <span class="filter-label-text"> <?php echo $item->getCatName() ? html_entity_decode($block
                                    ->escapeHtml($item->getCatName(), ['span'])) :html_entity_decode($block
                                    ->escapeHtml($item->getLabel(), ['span'])) ?></span>
                            <?php if ($block->getHelper()->isShowValueQty()) : ?>
                                <span class="count"><?php echo (int)$item->getCount() ?><span
                                            class="filter-count-label">
                                <?php
                                if ($item->getCount() == 1) :
                                    ?>
                                    <?php echo __('item') ?>
                                <?php else : ?>
                                    <?php echo __('items') ?>
                                <?php endif; ?></span></span>
                            <?php endif; ?>
                </span>
                    <?php endif; ?>
                </a>
            <?php endif; ?>
        </li>
        <?php $cnt++; ?>
    <?php endforeach ?>
    <?php if ($filter->isActive() && $filter->getGomageIsReset() ||
        ($filter->isActive() && $filter->isCategoryFilter() && $categoriesHelper->isShowResetLink())) : ?>
        <a
                data-role="navigation-filter"
                data-value=""
                data-url="<?php echo $block->escapeUrl($filter->getRemoveUrl()) ?>"
                data-param-to-remove="<?php echo $block->escapeHtml($filter->getRequestVar()) ?>"
            <?php if ($filter->getGomageIsAjax() || null === ($filter->getGomageIsAjax()) &&
                (($filter->isCategoryFilter() && $categoriesHelper->isAjax()) || !$filter->isCategoryFilter())) : ?>
                data-ajax="1"
            <?php else : ?>
                data-ajax="0"
            <?php endif; ?>
                data-type="remove-item"
                data-active="1"
                href="#"
                class="gan_link_reset">
            <?php echo __('Reset'); ?>
        </a>
    <?php endif; ?>
    <?php if ($optionsLimit && count($filterItems) > $optionsLimit) : ?>
        <li style=" <?php echo ($helperData->isShowMore($filter->getName())) ? 'display:none' : '' ?>"
            data-show-more="<?php echo $helperData->isShowMore($filter->getName()) ?>"
            data-more-value="<?php echo strtolower($filter->getName()); ?>" data-more-params="more_show"
            class="gan_link_more"><a href="javascript:void(0)"><?php echo __('More') ?>&#9660;</a></li>
        <li class="gan_link_more_less" <?php echo (!$helperData->isShowMore($filter->getName()))
            ? 'display:none' : '' ?>>
            <a href="javascript:void(0)"><?php echo __('Less') ?>&#9650;</a></li>
    <?php endif; ?>
</ol>
