
<?php
/**
 *
 * @var $block \GoMage\Navigation\Block\Navigation\FilterRenderer
 */

$filter = reset($filterItems)->getFilter();
$attributeModel = $filter->getAttributeModel();
$priceValues = explode(';', $filter->getSingleValue());
?>

<div class="gan-filter gan-filter-input">
    <form>
        <input
               class="gan-price"
               style="display: none;"
               data-role="navigation-filter"
               data-active=""
               data-from="<?= $block->escapeHtml($filter->getMinBasePrice()); ?>"
               data-to="<?= $block->escapeHtml($filter->getMaxBasePrice()); ?>"
               data-code="<?= $block->escapeHtml($filter->getAttributeModel()->getAttributeCode()); ?>"
               data-param="<?=$block->escapeHtml($filter->getRequestVar()) ?>"
            <?php if  ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                data-ajax="1"
            <?php else: ?>
                data-ajax="0"
            <?php endif;?>
               id="<?= $block->escapeHtml($filter->getAttributeModel()->getAttributeCode()); ?>"
               value="<?= $block->escapeHtml($filter->getSingleValue()) ?>"/>
        <fieldset class="gan-filter-input-fieldset">

            <div class="gan-filter-input-fields">
                <div class="from-wrapper">
                    <label>
                        <input
                                class="price-from"
                            <?php if(!$filter->getGomageIsShowFilterButton()):?>
                                data-role="navigation-filter"
                                data-type="input-price"
                            <?php endif;?>
                            <?php if  ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                                data-ajax="1"
                            <?php else: ?>
                                data-ajax="0"
                            <?php endif;?>
                                type="text"
                                value="<?= $block->escapeHtml($priceValues[0]); ?>"
                                name="<?= $block->escapeHtml($attributeModel->getAttributeCode());?>_from"
                                />
                    </label>
                </div>
                <div class="to-text-wrapper">
                    <span><?= __('to')?></span>
                </div>
                <div class="to-wrapper">
                    <label>
                        <input class="price-to"
                            <?php if(!$filter->getGomageIsShowFilterButton()):?>
                               data-role="navigation-filter"
                               data-type="input-price"
                            <?php endif;?>
                            <?php if  ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                                data-ajax="1"
                            <?php else: ?>
                                data-ajax="0"
                            <?php endif;?>
                                type="text"
                                value="<?= $block->escapeHtml($priceValues[1]); ?>"
                                name="<?= $block->escapeHtml($attributeModel->getAttributeCode());?>_to"
                                />
                    </label>
                </div>
            </div>

            <?php if($filter->getGomageIsShowFilterButton()):?>
                <div class="gan-filter-input-actions">
                    <button
                            class="price-button"
                            data-role="navigation-filter"
                            data-type="price-button"
                            class="gan-custom-button"
                            type="submit"
                        <?php if  ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                            data-ajax="1"
                        <?php else: ?>
                            data-ajax="0"
                        <?php endif;?>
                            style="
                            <?php if ($block->getNavigationViewHelper()->isNavigationViewButtonsGradient() && !empty($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor2())):?>
                                    background: linear-gradient(to bottom, <?=$block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor()?>, <?=$block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor2()?>);
                                    <?php elseif(!empty($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor())):?>
                                    background: <?=$block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor()?>;
                                    <?php endif;?>
                            <?php if (!empty($block->getNavigationViewHelper()->getNavigationViewButtonsTextColor())):?>
                                    color: <?=$block->getNavigationViewHelper()->getNavigationViewButtonsTextColor()?>
                                    <?php endif;?>
                                    ">

                        <span><?= __('Filter'); ?></span>
                    </button>
                </div>
            <?php endif;?>
            <?php if ($filter->isActive() && $filter->getGomageIsReset()):?>
                <a
                        data-role="navigation-filter"
                        data-param-to-remove="<?=$block->escapeHtml($filter->getRequestVar()) ?>"
                        data-value=""
                        data-url="<?= $block->escapeUrl($filter->getRemoveUrl()) ?>"
                    <?php if  ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                        data-ajax="1"
                    <?php else: ?>
                        data-ajax="0"
                    <?php endif;?>
                        data-type="remove-item"
                        data-active="1"
                        href="#"
                        class="gan_link_reset">
                    <?= __('Reset'); ?>
                </a>
            <?php endif;?>

        </fieldset>
    </form>
</div>
