
<?php
/**
 *
 * @var $block \GoMage\Navigation\Block\Navigation\FilterRenderer
 */

$filter = reset($filterItems)->getFilter();
$attributeModel = $filter->getAttributeModel();
$priceValues = explode(';', $filter->getSingleValue());
?>

<div class="gan-filter gan-filter-input">
    <?=$block->getTooltip($filter)->toHtml()?>
    <form>
        <input style="display: none;"
               data-role="navigation-filter"
               data-active=""
               data-from="<?php echo $filter->getMinBasePrice(); ?>"
               data-to="<?php echo $filter->getMaxBasePrice(); ?>"
               data-code="<?php echo $filter->getAttributeModel()->getAttributeCode(); ?>"
               data-param="<?php echo $filter->getRequestVar() ?>"
            <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                data-ajax="1"
            <?else:?>
                data-ajax="0"
            <?endif;?>
               id="<?php echo $filter->getAttributeModel()->getAttributeCode(); ?>"
               value="<?php echo $filter->getSingleValue() ?>"/>
        <fieldset class="gan-filter-input-fieldset">

            <div class="gan-filter-input-fields">
                <div class="from-wrapper">
                    <label>
                        <input
                                id="price-from"
                            <?php if(!$filter->getGomageIsShowFilterButton()):?>
                                data-role="navigation-filter"
                                data-type="input-price"
                            <?endif;?>
                            <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                                data-ajax="1"
                            <?else:?>
                                data-ajax="0"
                            <?endif;?>
                                type="text"
                                value="<?php echo $priceValues[0]; ?>"
                                name="<?php echo $attributeModel->getAttributeCode();?>_from"
                                />
                    </label>
                </div>
                <div class="to-text-wrapper">
                    <span><?php echo __('to')?></span>
                </div>
                <div class="to-wrapper">
                    <label>
                        <input id="price-to"
                            <?php if(!$filter->getGomageIsShowFilterButton()):?>
                               data-role="navigation-filter"
                               data-type="input-price"
                            <?endif;?>
                            <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                                data-ajax="1"
                            <?else:?>
                                data-ajax="0"
                            <?endif;?>
                                type="text"
                                value="<?php echo $priceValues[1]; ?>"
                                name="<?php echo $attributeModel->getAttributeCode();?>_to"
                                />
                    </label>
                </div>
            </div>

            <?php if($filter->getGomageIsShowFilterButton()):?>
                <div class="gan-filter-input-actions">
                    <button
                            id="price-button"
                            data-role="navigation-filter"
                            data-type="price-button"
                            class="gan-custom-button"
                            type="submit"
                        <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                            data-ajax="1"
                        <?else:?>
                            data-ajax="0"
                        <?endif;?>
                            style="
                            <?if($block->getNavigationViewHelper()->isNavigationViewButtonsGradient() && !empty($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor2())):?>
                                    background: linear-gradient(to bottom, <?=$block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor()?>, <?=$block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor2()?>);
                                    <?elseif(!empty($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor())):?>
                                    background: <?=$block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor()?>;
                                    <?endif;?>
                            <?if(!empty($block->getNavigationViewHelper()->getNavigationViewButtonsTextColor())):?>
                                    color: <?=$block->getNavigationViewHelper()->getNavigationViewButtonsTextColor()?>
                                    <?endif;?>
                                    ">

                        <span><?php echo __('Filter'); ?></span>
                    </button>
                </div>
            <?php endif;?>

        </fieldset>
    </form>
</div>