<?

/**
 * Template for filter items block
 *
 * @var $block \GoMage\Navigation\Block\Navigation\FilterRenderer
 */

$filter = reset($filterItems)->getFilter();

$priceValues = explode(';', $filter->getSingleValue());

?>

<div class="gan-filter gan-filter-slider gan-filter-slider-input">
    <div class="layout">
        <?=$block->getTooltip($filter)->toHtml()?>
        <div class="layout-slider">
            <span>
                <input style="display: none;"
                       data-role="navigation-filter"
                       data-active=""
                       data-from="<?= $block->escapeHtmlAttr($filter->getMinBasePrice()); ?>"
                       data-to="<?= $block->escapeHtmlAttr($filter->getMaxBasePrice()); ?>"
                       data-step="<?= $block->escapeHtmlAttr($block->getStep()); ?>"
                       data-skin="<?= $block->escapeHtmlAttr($block->getSliderSkin()); ?>"
                       data-code="<?= $block->escapeHtmlAttr($filter->getAttributeModel()->getAttributeCode()); ?>"
                       data-dimension="&nbsp;<?= $block->escapeHtmlAttr($filter->getCurrencySymbol()); ?>"
                       data-param="<?= $block->escapeHtmlAttr($filter->getRequestVar()) ?>"
                        <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                            data-ajax="1"
                        <?else:?>
                            data-ajax="0"
                        <?endif;?>
                       id="<?= $block->escapeHtmlAttr($filter->getAttributeModel()->getAttributeCode()); ?>"
                       data-type="slider"
                       type="slider"
                       name="<?= $block->escapeHtmlAttr($filter->getAttributeModel()->getAttributeCode()); ?>"
                       value="<?= $block->escapeHtmlAttr($filter->getSingleValue()) ?>"/>
            </span>
        </div>
    </div>
    <div class="gan-filter gan-filter-input">
        <form>
            <fieldset class="gan-filter-input-fieldset">
                <div class="gan-filter-input-fields">
                    <div class="from-wrapper">
                        <label>
                            <input id="price-from"
                                   <? if(!$filter->getGomageIsShowFilterButton()):?>
                                       data-role="navigation-filter"
                                       data-type="input-price"
                                   <? endif;?>
                                   type="text"
                                   value="<?= $block->escapeHtml($priceValues[0]); ?>" />
                        </label>
                    </div>
                    <div class="to-text-wrapper">
                        <span><?= __('to')?></span>
                    </div>
                    <div class="to-wrapper">
                        <label>
                            <input id="price-to"
                                   <? if(!$filter->getGomageIsShowFilterButton()):?>
                                       data-role="navigation-filter"
                                       data-type="input-price"
                                   <? endif;?>
                                   type="text"
                                   value="<?= $block->escapeHtmlAttr($priceValues[1]); ?>" />
                        </label>
                    </div>
                </div>
                <? if($filter->getGomageIsShowFilterButton()):?>
                    <div class="gan-filter-input-actions">
                        <button id="price-button" data-role="navigation-filter" data-type="price-button" class="gan-custom-button" type="submit"
                                style="
                                    <?if($block->getNavigationViewHelper()->isNavigationViewButtonsGradient() && !empty($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor2())):?>
                                        background: linear-gradient(to bottom, <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor())?>, <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor2())?>);
                                    <?elseif(!empty($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor())):?>
                                        background: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewButtonsBackgroundColor())?>;
                                    <?endif;?>
                                    <?if(!empty($block->getNavigationViewHelper()->getNavigationViewButtonsTextColor())):?>
                                        color: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewButtonsTextColor())?>
                                    <?endif;?>
                        ">
                            <span><?= __('Filter'); ?></span>
                        </button>
                    </div>
                <? endif;?>
            </fieldset>
        </form>
        <?if($filter->isActive() && $filter->getGomageIsReset()):?>
            <a
                    data-role="navigation-filter"
                    data-value=""
                    data-url="<?= $block->escapeUrl($filter->getRemoveUrl()) ?>"
                    data-param="<?=$block->escapeHtmlAttr($filter->getRequestVar()) ?>"
                <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                    data-ajax="1"
                <?else:?>
                    data-ajax="0"
                <?endif;?>
                    data-type="remove-item"
                    data-active="1"
                    href="#">
                <?= __('Reset'); ?>
            </a>
        <?endif;?>
    </div>
</div>
<style type="text/css">
    
    <?if($block->getNavigationViewHelper()->getNavigationViewSliderLineHeight() < $block->getNavigationViewHelper()->getNavigationViewSliderElementHeight()):?>
    .gan-filter-slider .layout{
        padding-bottom:<?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewSliderElementHeight())?>px;
        margin-left: <?=$block->escapeHtmlAttr(($block->getNavigationViewHelper()->getNavigationViewSliderElementWidth() / 2))?>px;
        margin-right: <?=$block->escapeHtmlAttr(($block->getNavigationViewHelper()->getNavigationViewSliderElementWidth() / 2))?>px;
    }
    .gan-filter-slider .jslider .jslider-label,
    .gan-filter-slider .jslider .jslider-value{
        margin-top: <?= $block->escapeHtmlAttr((($block->getNavigationViewHelper()->getNavigationViewSliderElementHeight() - $block->getNavigationViewHelper()->getNavigationViewSliderLineHeight()) / 2 + 10)) ?>px;
    }
    <?endif;?>

    .gan-filter-slider .jslider .jslider-bg,
    .gan-filter-slider .jslider .jslider-bg .f,
    .gan-filter-slider .jslider .jslider-bg .r,
    .gan-filter-slider .jslider .jslider-bg .l,
    .gan-filter-slider .jslider .jslider-bg .v{

        /* Slider Line Height */
        height: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewSliderLineHeight())?>px;
        
    }
    
    .gan-filter-slider .jslider .jslider-bg .v{
        
        /* Slider Line Color */
        background: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewSliderLineColor())?>;

    }
    
    .gan-filter-slider .jslider_round_plastic .jslider-pointer{
        
        /* Slider Element Color */
        background: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewSliderElementColor())?>;
        
        /* Slider Element Width */
        width: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewSliderElementWidth())?>px;
        
        /* Slider Element Height */
        height: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewSliderElementHeight())?>px;
        
        /* Slider Element Radius */
        border-radius: <?=$block->escapeHtmlAttr($block->getNavigationViewHelper()->getNavigationViewSliderElementRadius())?>px;

    }
    
</style>