<?php
/**
 * Template for filter items block
 *
 * @var $block \GoMage\Navigation\Block\Navigation\FilterRenderer
 */

$filter = reset($filterItems)->getFilter();

?>

<div class="gan-filter gan-filter-slider">
    <?php $attributeCode = $filter->getAttributeModel()->getAttributeCode(); ?>
        <div class="layout">
            <div class="layout-slider">
                <span>
                    <input style="display: none;"
                           data-role="navigation-filter"
                        <?php if (!empty($filter->isActive())): ?>
                            data-active="1"
                        <?php endif; ?>
                           data-param="<?= $block->escapeHtml($filter->getRequestVar()) ?>"
                           data-from="<?= $block->escapeHtml($filter->getMinBasePrice()); ?>"
                           data-to="<?= $block->escapeHtml($filter->getMaxBasePrice()); ?>"
                           data-step="<?= $block->escapeHtml($block->getStep()); ?>"
                           data-skin="<?= $block->escapeHtml($block->getSliderSkin()); ?>"
                           data-code="<?= $block->escapeHtml($attributeCode); ?>"
                           data-dimension="&nbsp;<?= $block->escapeHtml($filter->getCurrencySymbol()); ?>"
                           data-param-to-remove="<?= $block->escapeHtml($filter->getRequestVar()) ?>"
                           data-ajax="1"
                           id="<?= $block->escapeHtml($attributeCode); ?>"
                           data-type="slider"
                           type="slider"
                           name="<?= $block->escapeHtml($attributeCode); ?>"
                           value="<?= $block->escapeHtml($filter->getSingleValue()) ?>"
                           data-value="<?= $block->escapeHtml(str_replace(';', '-', $filter->getSingleValue())); ?>"
                    />
                </span>
            </div>
        </div>
    <?php if ($filter->isActive() && $filter->getGomageIsReset() || ($filter->isActive() &&$filter->isCategoryFilter() && $categoriesHelper->isShowResetLink() )):?>
        <a
                data-role="navigation-filter"
                data-value=""
                data-url="<?= $block->escapeUrl($filter->getRemoveUrl()) ?>"
                data-param-to-remove="<?=$block->escapeHtml($filter->getRequestVar()) ?>"
            <?php if  ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax()) && ( ($filter->isCategoryFilter() &&  $categoriesHelper->isAjax()) ||  !$filter->isCategoryFilter()) ):?>
                data-ajax="1"
            <<?php else: ?>
                data-ajax="0"
            <?php endif;?>
                data-type="remove-item"
                data-active="1"
                href="#"
                class="gan_link_reset">
            <?= __('Reset'); ?>
        </a>
    <?php endif;?>
</div>