<?php
/**
 * GoMage.com
 *
 * GoMage Navigation M2
 *
 * @category  Extension
 * @copyright Copyright (c) 2018-2018 GoMage.com (https://www.gomage.com)
 * @author    GoMage.com
 * @license   https://www.gomage.com/licensing  Single domain license
 * @terms     of use https://www.gomage.com/terms-of-use
 * @version   Release: 1.0.0
 * @since     Class available since Release 1.0.0
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
?>

<?php
$filter = reset($filterItems)->getFilter();
$swatchData = $block->getSwatch()->setSwatchFilter($filter)->getSwatchData();
$swatchData = $block->prepareSwatchesData($swatchData, $filterItems);
$optionsLimit = ($filter->getGomageVisibleOptions()) ? $filter->getGomageVisibleOptions() : false;
$helperImageSwatch = $this->helper('GoMage\Navigation\Helper\ImageSwatchHelper');
$helperData = $this->helper('GoMage\Navigation\Helper\Data');
$cnt = 0;
?>

<div class="swatch-attribute swatch-layered <?=$block->escapeHtml($swatchData['attribute_code']) ?>"
     attribute-code="<?=$block->escapeHtml($swatchData['attribute_code']) ?>" attribute-id="<?=$block->escapeHtml($swatchData['attribute_id']) ?>">
    <div class="swatch-attribute-options clearfix <?php echo $helperData->getOptionsAlignment((int)$filter->getGomageOptionsAlignment()); ?>">
        <?php foreach ($swatchData['options'] as $option => $data): ?>
            <?php
                $selected = '';
            ?>
            <a  <?php if(!$data['is_show']): ?> style="display: none" <?php endif; ?> href="<?=$block->escapeUrl($data['link']) ?>"
               data-role="navigation-filter"
                data-value="<?= (!empty($data['gomage_value'])) ? $data['gomage_value'] : $option; ?>"
               data-param="<?= $block->escapeHtml($filter->getRequestVar()) ?>"
                <?php if($filter->getGomageIsAjax()):?>
                data-ajax="1"
                <?php endif;?>
               data-type="<?= $block->escapeHtml($filter->getSwatchInputType()); ?>"
                <?php if (!empty($data['is_active'])) : ?>
                <?php $selected = 'selected';?>
               data-active="1"
                <?php endif; ?>
               class="swatch-option-link-layered">
                <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="<?= $block->escapeHtml($selected);?> swatch-option  <?=(!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element': '' ?> <?=$block->escapeHtml($data['custom_style']) ?>"
                                 style="<?=((!empty(($optionsLimit) && $cnt >= $optionsLimit) && !$helperData->isShowMore($filter->getName()) )) ? 'display:none': '' ?>
                                 option-type="3"
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ></div>
                            <?php break;
                        case '2':
                            ?>
                            <?php $helperImageSwatch->setWidth($filter->getGomageImageWidth()); ?>
                            <?php $helperImageSwatch->setHeight($filter->getGomageImageHeight()); ?>
                            <?php $swatchThumbPath = $helperImageSwatch->getImagePath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']); ?>
                            <?php $swatchImagePath = $helperImageSwatch->getImagePath('swatch_image',
                            $swatchData['swatches'][$option]['value']); ?>
                            <div class="<?= $block->escapeHtml($selected);?> swatch-option  <?=(!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element': '' ?> image <?=$block->escapeHtml($data['custom_style']) ?>"
                                 option-type="2"
                                 style="<?=((!empty(($optionsLimit) && $cnt >= $optionsLimit) && !$helperData->isShowMore($filter->getName()) )) ? 'display:none': '' ?>
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb="<?=$block->escapeHtml($swatchThumbPath) ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?=$block->escapeUrl($swatchImagePath) ?>) no-repeat center; background-size: initial;
                                 <?= $block->escapeHtml(!empty($filter->getGomageImageWidth()) ? 'width:' . $filter->getGomageImageWidth() . 'px' : '');?>;
                                 <?= $block->escapeHtml(!empty($filter->getGomageImageHeight()) ? 'height:' . $filter->getGomageImageWidth() . 'px' : '');?>;">
                            </div>
                            <?php break;
                        case '1':
                            ?>
                            <div  class="<?= $block->escapeHtml($selected);?> swatch-option  <?=((!empty($optionsLimit) && $cnt >= $optionsLimit)) ? 'gan_link-more-element': '' ?> color <?=$block->escapeHtml($data['custom_style']) ?>"
                                 option-type="1"
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value="<?=$block->escapeHtml($swatchData['swatches'][$option]['value']) ?>"
                                 style="
                                 <?=((!empty(($optionsLimit) && $cnt >= $optionsLimit && !$helperData->isShowMore($filter->getName())))) ? 'display:none': '' ?>;
                                         background: <?=$block->escapeHtml($swatchData['swatches'][$option]['value']) ?> no-repeat center;
                                         background-size: initial;
                                        <?= $block->escapeHtml(!empty($filter->getGomageImageWidth()) ? 'width:' . $filter->getGomageImageWidth() . 'px' : '');?>;
                                        <?= $block->escapeHtml(!empty($filter->getGomageImageHeight()) ? 'height:' . $filter->getGomageImageWidth() . 'px' : '');?>;
                                         "></div>
                            <?php break;
                        case '0':
                        default:
                            ?>
                            <div class="<?= $block->escapeHtml($selected);?> swatch-option  <?=(!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element': '' ?> text <?=$block->escapeHtml($data['custom_style']) ?>"
                                 style="<?=((!empty(($optionsLimit) && $cnt >= $optionsLimit)) && !$helperData->isShowMore($filter->getName())) ? 'display:none': '' ?>"
                                 option-type="0"
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ><?=$block->escapeHtml($swatchData['swatches'][$option]['value']) ?></div>
                            <?php break;
                    } ?>
                <?php } ?>
            </a>
            <?php $cnt++;?>
        <?php endforeach; ?>
    </div>
    <?php if ($filter->isActive() && $filter->getGomageIsReset()):?>
        <a
                data-role="navigation-filter"
                data-value=""
                data-url="<?= $block->escapeUrl($filter->getRemoveUrl()) ?>"
                 data-param-to-remove="<?=$block->escapeHtml($filter->getRequestVar()) ?>"="<?=$block->escapeHtml($filter->getRequestVar()) ?>"
            <?php if  ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                data-ajax="1"
            <?php else: ?>
                data-ajax="0"
            <?php endif;?>
                data-type="remove-item"
                data-active="1"
                href="#"
                class="gan_link_reset">
            <?= __('Reset'); ?>
        </a>
    <?php endif;?>
</div>
<?php if($optionsLimit && count($filterItems) > $optionsLimit): ?>
<a style=" <?= ($helperData->isShowMore($filter->getName()) ) ? 'display:none': '' ?>" data-show-more = "<?php echo $helperData->isShowMore($filter->getName()) ?>" data-more-value = "<?php echo strtolower($filter->getName()); ?>" data-more-params="more_show" class="gan_link_more"><?=__('More') ?>&#9660;</a>
<a class="gan_link_more_less" style=" <?= (!$helperData->isShowMore($filter->getName()) ) ? 'display:none': '' ?>"><?=__('Less') ?>&#9650;</a>
<?php endif; ?>
<script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?=$block->escapeHtml($swatchData['attribute_code']) ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
