<?

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
?>

<?
$filter = reset($filterItems)->getFilter();
$swatchData = $block->getSwatch()->setSwatchFilter($filter)->getSwatchData();
$swatchData = $block->prepareSwatchesData($swatchData, $filterItems);
$optionsLimit = ($filter->getGomageVisibleOptions()) ? $filter->getGomageVisibleOptions() : false;
$helperImageSwatch = $this->helper('GoMage\Navigation\Helper\ImageSwatchHelper');
$helperData = $this->helper('GoMage\Navigation\Helper\Data');
$cnt = 0;
?>

<div class="swatch-attribute swatch-layered <?=$block->escapeHtml($swatchData['attribute_code']) ?>"
     attribute-code="<?=$block->escapeHtml($swatchData['attribute_code']) ?>" attribute-id="<?=$block->escapeHtml($swatchData['attribute_id']) ?>">
    <div class="swatch-attribute-options clearfix <?php echo $helperData->getOptionsAlignment((int)$filter->getGomageOptionsAlignment()); ?>">
        <? foreach ($swatchData['options'] as $option => $data): ?>
            <?
                $selected = '';
            ?>
            <a  <?php if(!$data['is_show']): ?> style="display: none" <?php endif; ?> href="<?=$block->escapeUrl($data['link']) ?>"
               data-role="navigation-filter"
                data-value="<?= (!empty($data['gomage_value'])) ? $data['gomage_value'] : $option; ?>"
               data-param="<?= $block->escapeHtml($filter->getRequestVar()) ?>"
                <? if($filter->getGomageIsAjax()):?>
                data-ajax="1"
                <?endif;?>
               data-type="<?= $block->escapeHtml($filter->getSwatchInputType()); ?>"
                <? if (!empty($data['is_active'])) : ?>
                <? $selected = 'selected';?>
               data-active="1"
                <? endif; ?>
               class="swatch-option-link-layered">
                <? if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <? switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="<?= $block->escapeHtml($selected);?> swatch-option  <?=(!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element': '' ?> <?=$block->escapeHtml($data['custom_style']) ?>"

                                 option-type="3"
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ></div>
                            <? break;
                        case '2':
                            ?>
                            <? $helperImageSwatch->setWidth($filter->getGomageImageWidth()); ?>
                            <? $helperImageSwatch->setHeight($filter->getGomageImageHeight()); ?>
                            <? $swatchThumbPath = $helperImageSwatch->getImagePath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']); ?>
                            <? $swatchImagePath = $helperImageSwatch->getImagePath('swatch_image',
                            $swatchData['swatches'][$option]['value']); ?>
                            <div class="<?= $block->escapeHtml($selected);?> swatch-option  <?=(!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element': '' ?> image <?=$block->escapeHtml($data['custom_style']) ?>"
                                 option-type="2"
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb="<?=$block->escapeHtml($swatchThumbPath) ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?=$block->escapeUrl($swatchImagePath) ?>) no-repeat center; background-size: initial;
                                 <?= $block->escapeHtml(!empty($filter->getGomageImageWidth()) ? 'width:' . $filter->getGomageImageWidth() . 'px' : '');?>;
                                 <?= $block->escapeHtml(!empty($filter->getGomageImageHeight()) ? 'height:' . $filter->getGomageImageWidth() . 'px' : '');?>;">
                            </div>
                            <? break;
                        case '1':
                            ?>
                            <div class="<?= $block->escapeHtml($selected);?> swatch-option  <?=(!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element': '' ?> color <?=$block->escapeHtml($data['custom_style']) ?>"
                                 option-type="1"
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value="<?=$block->escapeHtml($swatchData['swatches'][$option]['value']) ?>"
                                 style="
                                         background: <?=$block->escapeHtml($swatchData['swatches'][$option]['value']) ?> no-repeat center;
                                         background-size: initial;
                                        <?= $block->escapeHtml(!empty($filter->getGomageImageWidth()) ? 'width:' . $filter->getGomageImageWidth() . 'px' : '');?>;
                                        <?= $block->escapeHtml(!empty($filter->getGomageImageHeight()) ? 'height:' . $filter->getGomageImageWidth() . 'px' : '');?>;
                                         "></div>
                            <? break;
                        case '0':
                        default:
                            ?>
                            <div class="<?= $block->escapeHtml($selected);?> swatch-option  <?=(!empty($optionsLimit) && $cnt >= $optionsLimit) ? 'gan_link-more-element': '' ?> text <?=$block->escapeHtml($data['custom_style']) ?>"
                                 option-type="0"
                                 option-id="<?=$block->escapeHtml($option) ?>"
                                 option-label="<?=$block->escapeHtml($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ><?=$block->escapeHtml($swatchData['swatches'][$option]['value']) ?></div>
                            <? break;
                    } ?>
                <? } ?>
            </a>
            <?$cnt++;?>
        <? endforeach; ?>
    </div>
    <?if($filter->isActive() && $filter->getGomageIsReset()):?>
        <a
                data-role="navigation-filter"
                data-value=""
                data-url="<?= $block->escapeUrl($filter->getRemoveUrl()) ?>"
                data-param="<?=$block->escapeHtml($filter->getRequestVar()) ?>"
            <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                data-ajax="1"
            <?else:?>
                data-ajax="0"
            <?endif;?>
                data-type="remove-item"
                data-active="1"
                href="#">
            <?= __('Reset'); ?>
        </a>
    <?endif;?>
</div>
<?php if($optionsLimit): ?>
<a class="gan_link_more"><?=__('More') ?>&#9660;</a>
<a class="gan_link_more_less"><?=__('Less') ?>&#9650;</a>
<?php endif; ?>
<script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?=$block->escapeHtml($swatchData['attribute_code']) ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
