<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\LayeredNavigation\RenderLayered */
?>

<?php
$filter = reset($filterItems)->getFilter();
$swatchData = $block->getSwatch()->setSwatchFilter($filter)->getSwatchData();
$swatchData = $block->prepareSwatchesData($swatchData, $filterItems);
$optionsLimit = ($filter->getGomageVisibleOptions()) ? $filter->getGomageVisibleOptions() : false;
$cnt = 0;
?>

<div class="swatch-attribute swatch-layered <?=$block->escapeHtmlAttr($swatchData['attribute_code']) ?>"
     attribute-code="<?=$block->escapeHtmlAttr($swatchData['attribute_code']) ?>" attribute-id="<?=$block->escapeHtmlAttr($swatchData['attribute_id']) ?>">
    <div class="swatch-attribute-options clearfix">
        <?=$block->getTooltip($filter)->toHtml()?>
        <?php foreach ($swatchData['options'] as $option => $data): ?>
            <? if (!empty($optionsLimit) && $cnt >= $optionsLimit) {
                break;
            } ?>
            <?php
                if (!$data['is_show']) continue;
                $selected = '';
            ?>
            <a  href="<?=$block->escapeUrl($data['link']) ?>"
               data-role="navigation-filter"
                data-value="<?= (!empty($data['gomage_value'])) ? $data['gomage_value'] : $option; ?>"
               data-param="<?= $block->escapeHtmlAttr($filter->getRequestVar()) ?>"
                <?php if($filter->getGomageIsAjax()):?>
                data-ajax="1"
                <?endif;?>
               data-type="<?= $block->escapeHtmlAttr($filter->getSwatchInputType()); ?>"
                <? if (!empty($data['is_active'])) : ?>
                <?php $selected = 'selected';?>
               data-active="1"
                <? endif; ?>
               class="swatch-option-link-layered">
                <?php if (isset($swatchData['swatches'][$option]['type'])) { ?>
                    <?php switch ($swatchData['swatches'][$option]['type']) {
                        case '3':
                            ?>
                            <div class="<?= $block->escapeHtmlAttr($selected);?> swatch-option <?=$block->escapeHtmlAttr($data['custom_style']) ?>"

                                 option-type="3"
                                 option-id="<?=$block->escapeHtmlAttr($option) ?>"
                                 option-label="<?=$block->escapeHtmlAttr($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ></div>
                            <?php break;
                        case '2':
                            ?>
                            <?php $swatchThumbPath = $block->getSwatch()->getSwatchPath('swatch_thumb',
                            $swatchData['swatches'][$option]['value']); ?>
                            <?php $swatchImagePath = $block->getSwatch()->getSwatchPath('swatch_image',
                            $swatchData['swatches'][$option]['value']); ?>
                            <div class="<?= $block->escapeHtmlAttr($selected);?> swatch-option image <?=$block->escapeHtmlAttr($data['custom_style']) ?>"
                                 option-type="2"
                                 option-id="<?=$block->escapeHtmlAttr($option) ?>"
                                 option-label="<?=$block->escapeHtmlAttr($data['label']) ?>"
                                 option-tooltip-thumb="<?=$block->escapeHtmlAttr($swatchThumbPath) ?>"
                                 option-tooltip-value=""
                                 style="background: url(<?=$block->escapeUrl($swatchImagePath) ?>) no-repeat center; background-size: initial;"></div>
                            <?php break;
                        case '1':
                            ?>
                            <div class="<?= $block->escapeHtmlAttr($selected);?> swatch-option color <?=$block->escapeHtmlAttr($data['custom_style']) ?>"
                                 option-type="1"
                                 option-id="<?=$block->escapeHtmlAttr($option) ?>"
                                 option-label="<?=$block->escapeHtmlAttr($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value="<?=$block->escapeHtmlAttr($swatchData['swatches'][$option]['value']) ?>"
                                 style="background: <?=$block->escapeHtmlAttr($swatchData['swatches'][$option]['value']) ?> no-repeat center; background-size: initial;"></div>
                            <?php break;
                        case '0':
                        default:
                            ?>
                            <div class="<?= $block->escapeHtmlAttr($selected);?> swatch-option text <?=$block->escapeHtmlAttr($data['custom_style']) ?>"
                                 option-type="0"
                                 option-id="<?=$block->escapeHtmlAttr($option) ?>"
                                 option-label="<?=$block->escapeHtmlAttr($data['label']) ?>"
                                 option-tooltip-thumb=""
                                 option-tooltip-value=""
                            ><?=$block->escapeHtmlAttr($swatchData['swatches'][$option]['value']) ?></div>
                            <?php break;
                    } ?>
                <?php } ?>
            </a>
            <?$cnt++;?>
        <?php endforeach; ?>
    </div>
    <?if($filter->isActive() && $filter->getGomageIsReset()):?>
        <a
                data-role="navigation-filter"
                data-value=""
                data-url="<?= $block->escapeUrl($filter->getRemoveUrl()) ?>"
                data-param="<?=$block->escapeHtmlAttr($filter->getRequestVar()) ?>"
            <?if ($filter->getGomageIsAjax() || is_null($filter->getGomageIsAjax())):?>
                data-ajax="1"
            <?else:?>
                data-ajax="0"
            <?endif;?>
                data-type="remove-item"
                data-active="1"
                href="#">
            <?= __('Reset'); ?>
        </a>
    <?endif;?>
</div>

<script>
    require(["jquery", "jquery/ui", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-layered.<?=$block->escapeHtmlAttr($swatchData['attribute_code']) ?>')
            .find('[option-type="1"], [option-type="2"], [option-type="0"], [option-type="3"]')
            .SwatchRendererTooltip();
    });
</script>
