<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
$helper = $this->helper('GoMage\Navigation\Helper\Data');
$state = $this->getLayout()->createBlock('GoMage\Navigation\Block\Navigation\State');
$showMore = $this->getLayout()->createBlock('GoMage\Navigation\Block\Product\ProductList\More');
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?if ($helper->isEnable()):?>
    <div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('GoMage_Navigation::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('GoMage_Navigation::product/list/toolbar/amount.phtml')) ?>

        <?php echo $block->getPagerHtml() ?>

        <?php include ($block->getTemplateFile('GoMage_Navigation::product/list/toolbar/limiter.phtml')) ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('GoMage_Navigation::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>

        <?php echo $showMore->toHtml(); ?>
    </div>
    <?else:?>
    <div class="toolbar toolbar-products" data-mage-init='<?= /* @escapeNotVerified */ $block->getWidgetOptionsJson() ?>'>
        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?= $block->getPagerHtml() ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
    </div>
    <?endif;?>
<?php endif ?>
